#!/bin/bash

#SBATCH -J finetune_swin 
#SBATCH -t 4-00:00:00
#SBATCH -p dgx
#SBATCH -G 8
#SBATCH -N 1

# singularity or anaconda
export CONTAINERPATH=/lscratch/$(whoami)/containers/pt-caney-ft
if [ ! -d "$CONTAINERPATH" ]; then
  echo "$CONTAINERPATH does not exist, building."
  mkdir /lscratch/$(whoami)
  mkdir /lscratch/$(whoami)/containers
  module load singularity
  singularity build --sandbox /lscratch/$(whoami)/containers/pt-caney-ft docker://nasanccs/pytorch-caney:dev
fi

module load singularity

export PYTHONPATH=$PWD:$PWD/SimMIM
export NGPUS=8

srun -o $2 singularity exec --nv -B /explore,/panfs,/lscratch \
	$CONTAINERPATH \
	python -m torch.distributed.launch --nproc_per_node $NGPUS \
	SimMIM/modis_finetune.py \
	--cfg $1 \
	--pretrained $3 \
	--data-path /explore/nobackup/projects/ilab/data/satnet/training_* \
	--batch-size 256 \
	--output . \
	--amp-opt-level O0

