#!/bin/bash

#SBATCH --job-name=SATNET_FINETUNE    # create a short name for your job
#SBATCH --nodes=3
#SBATCH --ntasks-per-node=4      # total number of tasks per node
#SBATCH --gres=gpu:4            # number of gpus per node
#SBATCH --cpus-per-task=4        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem=240GB               # total memory per node 
#SBATCH --time=2-23:59:00          # total run time limit (HH:MM:SS)
#SBATCH --exclude=gpu014,gpu022



##### Number of total processes 
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX "
echo "Nodelist:= " $SLURM_JOB_NODELIST
echo "Number of nodes:= " $SLURM_JOB_NUM_NODES
echo "Ntasks per node:= "  $SLURM_NTASKS_PER_NODE
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX "

# If you want to load things from your .bashrc profile, e.g. cuda drivers, singularity etc 
source ~/.bashrc


# ******************* These are read internally it seems ***********************************
# ******** Master port, address and world size MUST be passed as variables for DDP to work 
export MASTER_PORT=$(expr 10000 + $(echo -n $SLURM_JOBID | tail -c 4))
export WORLD_SIZE=$(($SLURM_NNODES * $SLURM_NTASKS_PER_NODE))
echo "MASTER_PORT"=$MASTER_PORT
echo "WORLD_SIZE="$WORLD_SIZE

master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$master_addr
echo "MASTER_ADDR="$MASTER_ADDR

# Singularity or anaconda should work
module load anaconda
conda activate rapids-23.02

export PYTHONPATH=$PWD:$PWD/SimMIM

srun python	SimMIM/binary_finetune_multinode.py \
	--cfg $1 \
	--pretrained $2 \
	--data-path /explore/nobackup/projects/ilab/data/satnet/training_* \
	--batch-size 256 \
	--output . \
	--amp-opt-level O0

