MODEL:
  TYPE: swinv2
  NAME: simmim_tree_finetune
  DROP_PATH_RATE: 0.1
  SWINV2:
    IN_CHANS: 7
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 8
    PRETRAINED_WINDOW_SIZES: [ 12, 12, 12, 6 ]
DATA:
  IMG_SIZE: 128
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
TRAIN:
  EPOCHS: 800
  WARMUP_EPOCHS: 20
  BASE_LR: 1.25e-3
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.75
PRINT_FREQ: 50
SAVE_FREQ: 5
TAG: simmim_finetune__satnet_tree_swinv2_base__img192_window8__800ep_v4_ft
