MODEL:
  TYPE: swin
  NAME: simmim_finetune_modis_normed_10p
  DROP_PATH_RATE: 0.0
  SWIN:
    IN_CHANS: 7
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 6
DATA:
  IMG_SIZE: 192
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 20
  BASE_LR: 1.25e-3
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.9
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_finetune__10p__modis_swin_base__img192_window6__100ep_normed